#!/usr/bin/env bash
# Hand-assembled SwiftPM/xtool package for fixtures/hello-expo: the blueprint expo2spm will generate.
# Inputs: staged xcframeworks in ~/spike/fw (stage-frameworks.sh + pack-jsi-xcframework.sh) and the
# JS-side outputs in out/hello-expo (bundle -> main.hbc, ExpoModulesProvider, codegen, app.config).
# usage: slice-hello-expo.sh [build]
set -euo pipefail
export PATH="/usr/lib/swift/usr/bin:$HOME/.local/bin:$PATH"
ulimit -n 65536 || true

repo=/mnt/g/code/wslosx
nm=$repo/fixtures/hello-expo/node_modules
gen=$repo/out/hello-expo
fw=$HOME/spike/fw
app=$HOME/build/hello-expo
name=HelloExpo

mkdir -p "$app"
cd "$app"
rm -rf Sources Frameworks Resources
mkdir -p Sources Frameworks Resources

# Binary targets: SwiftPM wants them inside the package root.
binaries=(React ReactNativeDependencies hermesvm ExpoModulesCore ExpoModulesJSI ExpoFileSystem ExpoFont)
for b in "${binaries[@]}"; do ln -sfn "$fw/$b.xcframework" "Frameworks/$b.xcframework"; done

# React headers resolve through the xcframework's VFS overlay, as rncore.rb sets up for pods.
sed "s|\${ROOT_PATH}|$fw/React.xcframework|g" "$fw/React.xcframework/React-VFS-template.yaml" > react-vfs.yaml

# copy <src files...> into <dir>
put() { local dir=$1; shift; mkdir -p "$dir"; cp "$@" "$dir/"; }

# RN codegen (app-level): ReactCodegen + ReactAppDependencyProvider.
cg=$gen/codegen/build/generated/ios
put Sources/ReactCodegen "$cg"/ReactCodegen/*.mm
put Sources/ReactCodegen/include/ReactCodegen "$cg"/ReactCodegen/*.h
put Sources/ReactAppDependencyProvider "$cg"/ReactAppDependencyProvider/*.mm
put Sources/ReactAppDependencyProvider/include/ReactAppDependencyProvider "$cg"/ReactAppDependencyProvider/*.h

# expo: mixed pod, split ObjC (headers as <Expo/...>) and Swift. EXAppDelegatesLoader.m needs
# Expo-Swift.h (a cycle); it only registers the legacy app delegate wrapper, left out of the slice.
e=$nm/expo/ios
put Sources/ExpoObjC $(find "$e" -path "$e/Tests" -prune -o \( -name '*.m' -o -name '*.mm' \) -print | grep -v EXAppDelegatesLoader.m)
put Sources/ExpoObjC/include/Expo $(find "$e" -path "$e/Tests" -prune -o -name '*.h' -print | grep -v '/Swift.h$')
put Sources/Expo $(find "$e" -path "$e/Tests" -prune -o -name '*.swift' -print)
echo '@_exported import ExpoObjC' > Sources/Expo/_ObjCExports.swift

# expo-constants: same split.
c=$nm/expo-constants/ios
put Sources/EXConstantsObjC "$c"/*.m
put Sources/EXConstantsObjC/include/EXConstants "$c"/*.h
put Sources/EXConstants "$c"/*.swift
echo '@_exported import EXConstantsObjC' > Sources/EXConstants/_ObjCExports.swift

# Swift-only modules (spm.config.json: one swift target, ios/*.swift).
put Sources/ExpoAsset "$nm"/expo-asset/ios/*.swift
put Sources/ExpoKeepAwake "$nm"/expo-keep-awake/ios/*.swift

# App target: Expo template AppDelegate + generated provider.
put Sources/$name "$gen"/gen/ExpoModulesProvider.swift
tar -xzOf "$nm/expo/template.tgz" package/ios/HelloWorld/AppDelegate.swift > Sources/$name/AppDelegate.swift

cp "$gen/main.hbc" Resources/main.jsbundle
cp -r "$gen/EXConstants.bundle" Resources/
[ -d "$gen/assets" ] && [ -n "$(ls -A "$gen/assets")" ] && cp -r "$gen/assets" Resources/

# CocoaPods compiles every pod with a generated prefix header that pulls in UIKit for ObjC.
cat > cocoapods-prefix.h <<'H'
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif
H

cat > Package.swift <<SWIFT
// swift-tools-version: 6.0
// Generated by scripts/slice-hello-expo.sh. Do not edit.
import PackageDescription

let vfs = "$app/react-vfs.yaml"
let reactHeaders = "$fw/React.xcframework/Headers"
let depsHeaders = "$fw/ReactNativeDependencies.xcframework/Headers"
let hermesHeaders = "$fw/hermes-headers"

// Same defines CocoaPods gives RN-dependent pods (react_native_pods.rb get_folly_config + new arch).
let defines = ["-DFOLLY_NO_CONFIG=1", "-DFOLLY_MOBILE=1", "-DFOLLY_USE_LIBCPP=1", "-DFOLLY_CFG_NO_COROUTINES=1",
               "-DFOLLY_HAVE_CLOCK_GETTIME=1", "-DRCT_NEW_ARCH_ENABLED=1", "-DUSE_HERMES=1"]
let clangFlags = ["-ivfsoverlay", vfs, "-I\(reactHeaders)", "-I\(depsHeaders)", "-I\(hermesHeaders)",
                  "-Wno-incomplete-umbrella", "-Wno-nullability-completeness", "-fobjc-arc",
                  "-include", "$app/cocoapods-prefix.h"] + defines
let swiftFlags = ["-Xcc", "-ivfsoverlay", "-Xcc", vfs, "-Xcc", "-I\(reactHeaders)", "-Xcc", "-Wno-incomplete-umbrella"]

// Headers live in include/<headerDir>/ so <headerDir/X.h> works; quoted includes need the dir too.
func objc(_ name: String, headerDir: String? = nil, deps: [Target.Dependency]) -> Target {
    let own = "include/\(headerDir ?? name)"
    return .target(name: name, dependencies: deps, publicHeadersPath: "include",
                   cSettings: [.headerSearchPath(own), .unsafeFlags(clangFlags)],
                   cxxSettings: [.headerSearchPath(own), .unsafeFlags(clangFlags)])
}
func swift(_ name: String, deps: [Target.Dependency], implicitImport: String? = nil) -> Target {
    let implicit = implicitImport.map { ["-Xfrontend", "-import-module", "-Xfrontend", \$0] } ?? []
    return .target(name: name, dependencies: deps, swiftSettings: [.unsafeFlags(swiftFlags + implicit)])
}

let rn: [Target.Dependency] = ["React", "ReactNativeDependencies", "hermesvm"]
let core: [Target.Dependency] = rn + ["ExpoModulesCore", "ExpoModulesJSI"]

let package = Package(
    name: "$name",
    platforms: [.iOS("16.4")],
    products: [.library(name: "$name", targets: ["$name"])],
    targets: [
        $(for b in "${binaries[@]}"; do printf '.binaryTarget(name: "%s", path: "Frameworks/%s.xcframework"),\n        ' "$b" "$b"; done)
        objc("ReactCodegen", deps: rn),
        objc("ReactAppDependencyProvider", deps: rn + ["ReactCodegen"]),
        objc("ExpoObjC", headerDir: "Expo", deps: core),
        swift("Expo", deps: core + ["ExpoObjC"], implicitImport: "ExpoObjC"),
        objc("EXConstantsObjC", headerDir: "EXConstants", deps: core),
        swift("EXConstants", deps: core + ["EXConstantsObjC"], implicitImport: "EXConstantsObjC"),
        swift("ExpoAsset", deps: core),
        swift("ExpoKeepAwake", deps: core),
        swift("$name", deps: core + ["ExpoFileSystem", "ExpoFont", "Expo", "EXConstants", "ExpoAsset",
                                     "ExpoKeepAwake", "ReactAppDependencyProvider"]),
    ],
    cxxLanguageStandard: .cxx20
)
SWIFT

# Keys from Expo's template Info.plist that xtool doesn't set (RN's status bar module needs
# UIViewControllerBasedStatusBarAppearance=NO). xtool merges its own defaults on top.
cat > Info.plist <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDisplayName</key><string>Hello WSL</string>
  <key>CADisableMinimumFrameDurationOnPhone</key><true/>
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key><false/>
    <key>NSAllowsLocalNetworking</key><true/>
  </dict>
  <key>UIStatusBarStyle</key><string>UIStatusBarStyleDefault</string>
  <key>UIViewControllerBasedStatusBarAppearance</key><false/>
</dict>
</plist>
PLIST

cat > xtool.yml <<YML
version: 1
bundleID: com.dested.wslosx.helloexpo
product: $name
infoPath: Info.plist
resources:
  - Resources/main.jsbundle
  - Resources/EXConstants.bundle
YML

echo "assembled $app"
if [ "${1:-}" = build ]; then
  time xtool dev build 2>&1 | grep -v -E 'argument unused|^\s*$' | tail -60
fi
